name: Deploy to Snowflake

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set Environment Variables
      id: setenv
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "BRANCH_SUFFIX=_PROD" >> $GITHUB_ENV
        elif [[ "${{ github.ref_name }}" == "dev" ]]; then
          echo "BRANCH_SUFFIX=_DEV" >> $GITHUB_ENV
        else
          echo "BRANCH_SUFFIX=" >> $GITHUB_ENV
        fi
    - name: Install OpenSSL (for SnowSQL)
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl1.0.0
    - name: Install SnowSQL
      run: |
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
        SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

    - name: Run Deployment Script
      env:
        SNOWSQL_ACCOUNT: ${{ vars.SNOWFLAKE_ACCOUNT }}
        SNOWSQL_USER: ${{ vars.SNOWFLAKE_USER }}
        SNOWSQL_PWD: ${{ vars.SNOWFLAKE_PASSWORD }}
        ROLE: ${{ vars.SNOWFLAKE_ROLE }}
        WAREHOUSE: ${{ vars.SNOWFLAKE_WH }}
        DATABASE: ${{ vars.SNOWFLAKE_DB }}${{ env.BRANCH_SUFFIX }}
        SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}
      run:
        ~/bin/snowsql -q  "SELECT CURRENT_DATE;"
       # bash cicd/deploy.sh
