name: Deploy to Snowflake

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy to Snowflake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.21-linux_x86_64.bash
          bash snowsql-1.2.21-linux_x86_64.bash -y
          echo "$HOME/.snowsql" >> $GITHUB_PATH

      - name: Set Environment Variables
        id: setenv
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "BRANCH_SUFFIX=_PROD" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "BRANCH_SUFFIX=_DEV" >> $GITHUB_ENV
          else
            echo "BRANCH_SUFFIX=" >> $GITHUB_ENV
          fi

      - name: Run Deployment Script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          USER: ${{ secrets.SNOWFLAKE_USER }}
          ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          WAREHOUSE: ${{ secrets.SNOWFLAKE_WH }}
          DATABASE: ${{ secrets.SNOWFLAKE_DB }}${{ env.BRANCH_SUFFIX }}
          SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: bash cicd/deploy.sh
